apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: kafka-operator
  namespace: flux-system
spec:
  chart: solution-base/kafka/charts/kafka-operator
  sourceRef:
    name: zenko
    kind: GitRepository
  interval: 10m
