apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zookeeper-operator
  namespace: zookeeper-operator
spec:
  releaseName: zookeeper-operator
  chart:
    spec:
      chart: zookeeper-operator
      sourceRef:
        kind: HelmRepository
        name: pravega
        namespace: flux-system
      version: "0.2.7"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/values.yaml
  values:
    watchNamespace: all
