---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: zenko-operator-crds
  namespace: default
spec:
  targetNamespace: default
  interval: 5m
  path: solution/operator/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: zenko
    namespace: flux-system
  timeout: 2m
