apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: solutions/cert-manager/charts/cert-manager
      sourceRef:
        kind: GitRepository
        name: ringx
        namespace: default
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://artifacthub.io/packages/helm/jetstack/cert-manager
  values:
    installCRDs: true
