apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      version: "9.0.5"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-values
