apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: solutions/iam/keycloak/charts/
      sourceRef:
        kind: GitRepository
        name: ringx
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-values
